### ISSUE TITLE
Maven Compilation

### ISSUE THREAD

**Issue by kNoAPP** [allanmc/java-cue-sdk#3]
Good evening,
I'd like to use your API to hook my keyboard up to my server and have it flash when a specific action occurs. However, I can't get your maven setup to run correctly on my computer (I'm assuming because of wget, run, and generate). Would you happen to have a copy already compiled or a maven repository to this API I can use?

Thanks.

**Comment by allanmc** [comment]
Sorry for the late response. The SDK download was moved by Corsair, so it couldn't be downloaded by the Maven script anymore. I've updated it, and it's now using the latest SDK version 3.0.234.
